// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/inquiries","name":"询价需求","parentId":"@@/global-layout","id":"1"},"2":{"path":"/inquiries/:id","parentId":"@@/global-layout","id":"2"},"3":{"path":"/products","name":"商品库","parentId":"@@/global-layout","id":"3"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__inquiries__index" */'@/pages/inquiries/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__inquiries__id" */'@/pages/inquiries/[id].tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__products" */'@/pages/products.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/wuyuanchao/learnspace/dropshopping/src/layouts/index.tsx')),
},
  };
}
