// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { defaultContext, QueryClient, QueryClientProvider } from '/Users/wuyuanchao/learnspace/dropshopping/node_modules/@tanstack/react-query';
import { ReactQueryDevtools } from '/Users/wuyuanchao/learnspace/dropshopping/node_modules/@tanstack/react-query-devtools';
const reactQueryConfig = {};
const client = new QueryClient(reactQueryConfig.queryClient || {});
export function rootContainer(container) {
  return (
    <QueryClientProvider client={client} context={defaultContext}>
      {container}
      <ReactQueryDevtools context={defaultContext} initialIsOpen={false} {...(reactQueryConfig.devtool || {})} />
    </QueryClientProvider>
  );
}
